# At this time only the JSON subset of YAML is supported plus YAML-style
# comments (like this one)
{
    # axon geometry
    "axon_length"   : 1000,  # microns
    "axon_diameter" : 1,     # microns

    # temperature
    "axon_temperature" : 16,  # °C

    # axon electrical properties
    "initial_membrane_potential" : -65,     # mV
    "axial_resistance"           : 100,     # Ohm·cm² at 20°C
    "axial_resistance_T"         : 18.5,    # °C
    "axial_resistance_Q10"       : 0.76923, # Ohm·cm²
    "membrane_capacitance"       : 1,       # µF/cm²

    # simulation settings
    "num_sections"     : 1000,
    "max_time_step"    : 0.005, # ms
    "integration_time" : 3      # ms
}
