# At this time only the JSON subset of YAML is supported plus YAML-style
# comments (like this one)
{
    # axon geometry
    "axon_length"   : 1000,  # µm
    "axon_diameter" : 1,     # µm

    # temperature
    "axon_temperature" : 16,  # °C

    # axon electrical properties
    "initial_membrane_potential" : -65,     # mV
    "axial_resistance"           : 100,     # Ohm·cm² at 20°C
    "axial_resistance_T"         : 18.5,    # °C
    "axial_resistance_Q10"       : 0.76923, # Ohm·cm²
    "membrane_capacitance"       : 1,       # µF/cm²
    "g_Na_bar"                   : 8.0e-3,  # S/cm²
    "g_Na_persistent_bar"        : 0.54e-3, # S/cm²
    "g_K_bar"                    : 1.2e-3,  # S/cm²

    # simulation settings
    "num_sections"        : 1000,
    "max_time_step"       : 0.005, # ms
    "integration_time"    : 3,     # ms
    "param_sweep_steps"   : 1      # set to > 1 for a parameter sweep, then
                                   # use sweep_param and threshold_param with
                                   # interpolate to set the dependent and
                                   # independent variables (see example).
}
